export const IP_ADDRESS = '192.168.1.61';
export const PORT_API = '8080';
export const PORT_WEB_APP = '4200';
export const URL_CALL_API = 'http://' + IP_ADDRESS + ':' + PORT_API + '/api';
export const URL_AVATAR = 'http://' + IP_ADDRESS + ':' + PORT_API + '/api/images/avatar/';
export const URL_WEP_APP = 'http://' + IP_ADDRESS + ':' + PORT_WEB_APP + '/';
export const ADDRESS_SOCKET = 'ws://' + IP_ADDRESS + ':' + PORT_API + '/carpool/websocket?authorization=';
export const MAPBOX_KEY = 'pk.eyJ1IjoiZGFuZ21pbmhiazc3NyIsImEiOiJjanRsM2ltZmwzMm81NDVtdWhhM3RhYmJsIn0.6VYmuY3xP3IgEvT_Vc3pRQ';
export const URL_MAPBOX_API = 'https://api.mapbox.com/geocoding/v5/mapbox.places/';
export const URL_PAGE_LOGIN = '/login';
export const URL_PAGE_REGISTER = '/user/register';
export const DEFAULT_LOGIN = '/home';
export const AUTHORIZATION = "authorization";
